In [5]:
import os, glob
import numpy as np
from sklearn.svm import LinearSVC
import pandas as pd
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.utils import shuffle

In [6]:
def knn_classification(X_train, X_test, y_train, y_test ):
#    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

    knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)

    print(confusion_matrix(y_test, y_pred))
    print("accuracy:", accuracy_score(y_test, y_pred))
    print("precision: ", precision_score(y_test, y_pred, pos_label=1, average='micro'))
    print("recall: ", recall_score(y_test, y_pred, pos_label=1, average='micro'))

In [7]:
def LSVC_(data, label, n_features):
    """returns the features selected based on linearSVC,
    data. label should be numpy array"""
    lsvc = LinearSVC(C=1, penalty="l1", dual=False).fit(data, label)
    coef = np.squeeze(np.sum(np.square(np.array(lsvc.coef_)), axis=0))
    coefidx = np.argsort(coef)
    fidx = coefidx[-n_features:]
    return fidx

In [8]:
path = '/Users/fatemeh/Net_project/02-PreprocessedDatasets/' + '*.csv'   
files = glob.glob(path)
data = []
for file in files:
    data.append(pd.read_csv(file))
data = pd.concat(data)

In [9]:
columns_name = data.columns[0].split("\t")
data.columns = ['Col']
    
data = data.Col.apply(lambda x: pd.Series(str(x).split("\t")))
data = data.set_index(data.columns[0])
data.columns = columns_name[1:]
data = data.astype('int32')
#take the labels and remove it from dataset
label = data['wbcqi'].to_numpy()
data = data.drop(['wbcqi'], axis=1)

In [10]:
data, label = shuffle(data, label, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.25, random_state=1)
selected_indx = LSVC_(X_train, y_train, 10)
X_train = X_train[X_train.columns[list(selected_indx)]]
X_test = X_test[X_test.columns[list(selected_indx)]]
knn_classification(X_train, X_test, y_train, y_test) 

/Users/fmohebbi1/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[[   5    3    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   97    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    1   39    6    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0  151    3    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0  302    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0  498    6    0    0    0    0    0    0    0]
 [   0    0    1    0    0    0  859    1    0    0    0    0    0    0]
 [   0    0    0    0    0    0    3  483    1    0    0    0    0    0]
 [   0    0    0    0    0    0    0    2  219    1    0    0    1    0]
 [   0    0    0    0    0    0    0    0    4  119    0    0    0    0]
 [   0    0    0    0    0    0    0    0    3    0  216    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0  164    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    0   46    2]
 [   0    0    0    0    0    0    0    0    0    0